Authentication.Twitter/Models/ConfigurationModel.cs
using Grand.Infrastructure.ModelBinding;
using Grand.Infrastructure.Models;

namespace Authentication.Twitter.Models
{
    public class ConfigurationModel : BaseModel
    {
        [GrandResourceDisplayName("Authentication.Twitter.ConsumerKey")]
        public string ConsumerKey { get; set; }

        [GrandResourceDisplayName("Authentication.Twitter.ConsumerSecret")]
        public string ConsumerSecret { get; set; }

        [GrandResourceDisplayName("Authentication.Twitter.DisplayOrder")]
        public int DisplayOrder { get; set; }
    }
}

Authentication.Twitter/Models/FailedModel.cs
using Grand.Infrastructure.Models;

namespace Authentication.Twitter.Models
{
    public class FailedModel : BaseModel
    {
        public string ErrorCode { get; set; }
        public string ErrorMessage { get; set; }
    }
}

Authentication.Twitter/Areas/Admin/Controllers/TwitterAuthenticationSettingsController.cs
using Authentication.Twitter.Models;
using Grand.Business.Core.Interfaces.Common.Configuration;
using Grand.Business.Core.Interfaces.Common.Localization;
using Grand.Business.Core.Interfaces.Common.Security;
using Grand.Business.Core.Utilities.Common.Security;
using Grand.Web.Common.Controllers;
using Grand.Web.Common.Filters;
using Grand.Web.Common.Security.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Authentication.Twitter.Controllers
{
    [AuthorizeAdmin]
    [Area("Admin")]
    [PermissionAuthorize(PermissionSystemName.ExternalAuthenticationMethods)]
    public class TwitterAuthenticationSettingsController : BasePluginController
    {
        #region Fields

        private readonly TwitterExternalAuthSettings _TwitterExternalAuthSettings;
        private readonly ITranslationService _translationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IConfiguration _configuration;

        #endregion

        #region Ctor

        public TwitterAuthenticationSettingsController(TwitterExternalAuthSettings TwitterExternalAuthSettings,
            ITranslationService translationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IConfiguration configuration)
        {
            _TwitterExternalAuthSettings = TwitterExternalAuthSettings;
            _translationService = translationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _configuration = configuration;
        }

        #endregion

        #region Methods

        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.Authorize(StandardPermission.ManageExternalAuthenticationMethods))
                return AccessDeniedView();

            var model = new ConfigurationModel {
                ConsumerKey = _configuration["TwitterSettings:ConsumerKey"],
                ConsumerSecret = _configuration["TwitterSettings:ConsumerSecret"],
                DisplayOrder = _TwitterExternalAuthSettings.DisplayOrder
            };


            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.Authorize(StandardPermission.ManageExternalAuthenticationMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return await Configure();

            _TwitterExternalAuthSettings.DisplayOrder = model.DisplayOrder;

            await _settingService.SaveSetting(_TwitterExternalAuthSettings);

            //now clear settings cache
            await _settingService.ClearCache();

            Success(_translationService.GetResource("Admin.Plugins.Saved"));

            return await Configure();
        }


        #endregion
    }
}

Authentication.Twitter/Controllers/TwitterAuthenticationController.cs
using Authentication.Twitter.Models;
using Grand.Business.Core.Interfaces.Authentication;
using Grand.SharedKernel;
using Grand.Web.Common.Controllers;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Twitter;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Security.Claims;
using Grand.Business.Core.Utilities.Authentication;

namespace Authentication.Twitter.Controllers
{
    public class TwitterAuthenticationController : BasePluginController
    {
        #region Fields

        private readonly IExternalAuthenticationService _externalAuthenticationService;
        private readonly IConfiguration _configuration;

        #endregion

        #region Ctor

        public TwitterAuthenticationController(
            IExternalAuthenticationService externalAuthenticationService,
            IConfiguration configuration)
        {
            _externalAuthenticationService = externalAuthenticationService;
            _configuration = configuration;
        }

        #endregion

        #region Methods

        public IActionResult TwitterLogin(string returnUrl)
        {
            if (!_externalAuthenticationService.AuthenticationProviderIsAvailable(TwitterAuthenticationDefaults.ProviderSystemName))
                throw new GrandException("Twitter authentication module cannot be loaded");

            if (string.IsNullOrEmpty(_configuration["TwitterSettings:ConsumerKey"]) || string.IsNullOrEmpty(_configuration["TwitterSettings:ConsumerSecret"]))
                throw new GrandException("Twitter authentication module not configured");

            //configure login callback action
            var authenticationProperties = new AuthenticationProperties {
                RedirectUri = Url.Action("TwitterLoginCallback", "TwitterAuthentication", new { returnUrl })
            };

            return Challenge(authenticationProperties, TwitterDefaults.AuthenticationScheme);
        }

        public async Task<IActionResult> TwitterLoginCallback(string returnUrl)
        {
            //authenticate Twitter user
            var authenticateResult = await HttpContext.AuthenticateAsync(TwitterDefaults.AuthenticationScheme);
            if (!authenticateResult.Succeeded || !authenticateResult.Principal.Claims.Any())
                return RedirectToRoute("Login");

            //create external authentication parameters
            var authenticationParameters = new ExternalAuthParam {
                ProviderSystemName = TwitterAuthenticationDefaults.ProviderSystemName,
                AccessToken = await HttpContext.GetTokenAsync(TwitterDefaults.AuthenticationScheme, "access_token"),
                Email = authenticateResult.Principal.FindFirst(claim => claim.Type == ClaimTypes.Email)?.Value,
                Identifier = authenticateResult.Principal.FindFirst(claim => claim.Type == ClaimTypes.NameIdentifier)?.Value,
                Name = authenticateResult.Principal.FindFirst(claim => claim.Type == ClaimTypes.Name)?.Value,
                Claims = authenticateResult.Principal.Claims.ToList()
            };

            //authenticate Grand user
            return await _externalAuthenticationService.Authenticate(authenticationParameters, returnUrl);
        }
        public IActionResult TwitterSignInFailed(string error_code, string error_message, string state)
        {
            //handle exception and display message to user
            var model = new FailedModel() {
                ErrorCode = error_code,
                ErrorMessage = error_message
            };
            return View(model);
        }


        #endregion
    }
}

Authentication.Twitter/Areas/Admin/Views/TwitterAuthenticationSettings/Configure.cshtml
@model Authentication.Twitter.Models.ConfigurationModel
@{
    Layout = "_ConfigurePlugin";
}
<input id="active-menu-item" type="hidden" value="/Admin/ExternalAuthentication/Methods" />
<form asp-controller="TwitterAuthenticationSettings" asp-area="Admin" asp-action="Configure" method="post">

    <div class="form-horizontal">
        <div class="form-body">
            <div class="note note-info">
                <p>
                    To configure authentication with Twitter follow these steps:<br />
                    <br />
                    1. Navigate to the <a href="https://developers.Twitter.com/apps" target="_blank">Twitter for Developers</a> page and sign in. If you don't already have a Twitter account, use the <b>Sign up for Twitter</b> link on the login page to create one.<br />
                    2. Tap the <b>+ Add a New App button</b> in the upper right corner to create a new App ID. (If this is your first app with Twitter, the text of the button will be <b>Create a New App</b>.)<br />
                    3. Fill out the form and tap the <b>Create App ID button</b>.<br />
                    4. The <b>Product Setup</b> page is displayed, letting you select the features for your new app. Click <b>Get Started</b> on <b>Twitter Login</b>.<br />
                    5. Click the <b>Settings</b> link in the menu at the left, you are presented with the <b>Client OAuth Settings</b> page with some defaults already set.<br />
                    6. Enter "@("https://yourstore.com/signin-Twitter")" into the <b>Valid OAuth Redirect URIs</b> field.<br />
                    7. Click <b>Save Changes</b>.<br />
                    8. Click the <b>Dashboard</b> link in the left navigation.<br />
                    9. Copy your App ID and App secret below.<br />
                </p>
                <p>
                    <br /><br />
                    To edit Twitter settings in the grandnode application, please open the file App_Settings.json, 
                    find section TwitterSettings and enter the correct values.
                </p>
            </div>
            <div class="form-group">
                <div class="col-md-3 col-sm-3 text-right">
                    <admin-label asp-for="ConsumerKey" class="control-label" />
                </div>
                <div class="col-md-9 col-sm-9">
                    <input asp-for="ConsumerKey" type="text"
                        disabled class="form-control k-input text-box single-line" />
                    <span asp-validation-for="ConsumerKey"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3 col-sm-3 text-right">
                    <admin-label asp-for="ConsumerSecret" class="control-label" />
                </div>
                <div class="col-md-9 col-sm-9">
                    <input asp-for="ConsumerSecret" type="text" disabled class="form-control k-input text-box single-line" />
                    <span asp-validation-for="ConsumerSecret"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3 col-sm-3 text-right">
                    <admin-label asp-for="DisplayOrder" class="control-label" />
                </div>
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="DisplayOrder" />
                    <span asp-validation-for="DisplayOrder"></span>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <div class="row">
                <div class="offset-md-3 offset-sm-3 col-md-9 col-sm-9">
                    <input type="submit" name="save" class="btn green" value="@Loc["Admin.Common.Save"]" />
                </div>
            </div>
        </div>
    </div>
</form>

Authentication.Twitter/Views/Shared/Components/TwitterAuthentication/Default.cshtml
@using Grand.Web.Common.Page
@{
    Layout = "";
}
<div class="twitter-login-block">
    <div class="buttons">
        <a href="@Url.Action("TwitterLogin", "TwitterAuthentication", new { ReturnUrl = Context.Request.Query["ReturnUrl"].ToString()})" >Twitter</a>
    </div>
</div>

Authentication.Twitter/Views/TwitterAuthentication/TwitterSignInFailed.cshtml
@{
    Layout = "_SingleColumn";
}
@model Authentication.Twitter.Models.FailedModel
<div class="page Twitter-login">
    <div class="page-title">
        <h1>@Loc["Authentication.Twitter.Failed"]</h1>
    </div>
    <div class="page-body">
        <div class="alert alert-danger">
            @Loc["Authentication.Twitter.Failed.ErrorCode"]: @Model.ErrorCode <br>
            @Loc["Authentication.Twitter.Failed.ErrorMessage"]: @Model.ErrorMessage
        </div>
    </div>
</div>